#include "RCOutput_Duff.h"

#include <AP_HAL/AP_HAL.h>
#include <AP_Math/AP_Math.h>

#include <unistd.h>

extern const AP_HAL::HAL& hal;

using namespace Linux;

void RCOutput_Duff::init()
{
    // Initialise the pin low before the worker starts. That avoids a brief
    // unintended high pulse during boot or if init() is called before the
    // channel is explicitly enabled by the vehicle code.
    hal.gpio->pinMode(PWM_GPIO, HAL_GPIO_OUTPUT);
    hal.gpio->write(PWM_GPIO, 0);

    // The PWM waveform needs timing independent from the main ArduPilot loop,
    // so it is generated by a background pthread. init() may be reached more
    // than once in some HAL flows; starting a second thread would make two
    // loops fight over the same GPIO and corrupt the waveform.
    if (!_thread_started) {
        const int ret = pthread_create(&_thread, nullptr, thread_trampoline, this);
        if (ret == 0) {
            _thread_started = true;
        } else {
            hal.console->printf("RCOutput_Duff: pthread_create failed: %d\n", ret);
        }
    }
}

void RCOutput_Duff::set_freq(uint32_t chmask, uint16_t freq_hz)
{
    // RCOutput frequency changes are requested with a channel mask, but this
    // experimental backend has only one physical GPIO output. Apply the
    // requested frequency regardless of which logical channel was in the mask
    // so any SERVOx_FUNCTION mapping can be observed on GPIO18.
    (void)chmask;

    // Keep the frequency non-zero to avoid division by zero in pwm_loop(), and
    // cap it at the normal ArduPilot PWM upper range used by SRV_Channels.
    _freq_hz.store(constrain_uint16(freq_hz, 1, 400));
}

void RCOutput_Duff::enable_ch(uint8_t ch)
{
    // Do not filter on channel here. The goal is to log which logical output
    // reached the backend while still driving the single GPIO18 PWM output.
    hal.console->printf("RCOutput_Duff: enable ch=%u\n", unsigned(ch));
    _enabled.store(true);
}

void RCOutput_Duff::disable_ch(uint8_t ch)
{
    // Any disable request stops the single physical output, because there is no
    // per-channel state behind GPIO18 in this experiment.
    hal.console->printf("RCOutput_Duff: disable ch=%u\n", unsigned(ch));
    _enabled.store(false);
    hal.gpio->write(PWM_GPIO, 0);
}

void RCOutput_Duff::write(uint8_t ch, uint16_t period_us)
{
    // The caller supplies a final PWM pulse width, not a normalised throttle.
    // Clamp here so the software GPIO generator cannot produce out-of-range
    // servo/ESC pulses if a wider RCOutput value reaches this minimal backend.
    const uint16_t pwm_us = constrain_uint16(period_us, MIN_PWM_US, MAX_PWM_US);
    hal.console->printf("RCOutput_Duff: write ch=%u pwm=%u\n", unsigned(ch), unsigned(pwm_us));
    _pwm_us.store(pwm_us);
}

uint16_t RCOutput_Duff::read(uint8_t ch)
{
    // There is only one stored output value, so return it for any channel. This
    // matches the experimental "ignore channel, drive GPIO18" behavior.
    hal.console->printf("RCOutput_Duff: read ch=%u\n", unsigned(ch));
    return _pwm_us.load();
}

void *RCOutput_Duff::thread_trampoline(void *arg)
{
    static_cast<RCOutput_Duff *>(arg)->pwm_loop();
    return nullptr;
}

void RCOutput_Duff::pwm_loop()
{
    // There is no shutdown path because the HAL RCOutput object lives for the
    // process lifetime. Keeping one persistent worker also avoids create/destroy
    // jitter each time the channel is enabled.
    while (true) {
        if (!_enabled.load()) {
            // Disabled output should be electrically quiet. The 20ms sleep is
            // the default 50Hz servo frame length, long enough to avoid a busy
            // loop while still responding quickly to enable_ch().
            hal.gpio->write(PWM_GPIO, 0);
            usleep(20000);
            continue;
        }

        // Snapshot frequency and pulse width once per frame. This keeps each
        // generated frame internally consistent even if the main thread updates
        // the requested PWM while this loop is sleeping.
        const uint16_t freq_hz = _freq_hz.load();
        const uint32_t frame_us = 1000000UL / freq_hz;
        const uint32_t high_us = MIN(uint32_t(_pwm_us.load()), frame_us);
        const uint32_t low_us = frame_us - high_us;

        // Generate one software PWM frame. This is simple and portable for the
        // Duff experiment, but Linux scheduling means it is not as precise as a
        // hardware PWM peripheral.
        hal.gpio->write(PWM_GPIO, 1);
        usleep(high_us);

        hal.gpio->write(PWM_GPIO, 0);
        usleep(low_us);
    }
}
